### ISSUE TITLE
the script blocks all google ads

### ISSUE THREAD

**Issue by lucop1** [appnexus/cmp#74] opened 2018-05-25 10:20 UTC
A very strange behaviour happen with the script in page.
When the script is on the page with or without accepting the cookie all the advertising from google network doesn't appear.

If I remove the script from the page everything works as expected.

what can be the cause?

**Comment by krishoyt** [comment] 2018-05-25 15:16
Sounds like maybe the ad script is calling out to a CMP and expecting something before loading?  If you can post an example that reproduces this behavior I would like to see it.

**Comment by mercuryyy** [comment] 2018-05-26 17:39
@krishoyt  you might be using cmp.complete.build use cmp.build should fit it.

At least for me it did.

**Comment by lucop1** [comment] 2018-05-28 08:54
@mercuryyy so using cmp.build instead of cmp.complete.build solved the issue of google ads not showing?

**Comment by jsonUK** [comment] 2018-05-29 09:02
Why would you use cmp.bundle and not cmp.complete? Without cmp.complete you have no triggers to launch the CMP consent window.

We are seeing this behaviour on https://namemc.com where Google Ad's won't show until they accept cookies, then it triggers them to load. Is this from Google's end?

**Comment by lucop1** [comment] 2018-05-29 14:31
hi @jsonUK  thanks for your feedback. Did you develop the cmp solution on namemc.com ? Because it seems that they are using AppNexus cmp but highly customized.
Using the standard solution provided in this repo I'm still facing the issue of not showing Google Ads.
My flow is the following:
Show the CMP banner
if the user accepts I reload the page and enable the tags

but google now showing ads. If I don't include the JS code with the CMP everything works fine.

**Comment by andreyroth** [comment] 2018-05-30 16:25
I can't seem to reproduce this issue on https://namemc.com/. I've had reports from other users with the same bug, and am trying to investigate this further. @lucop1 mind sharing what is your OS, Browser and perhaps the log from the console when the bug happens?

**Comment by jsonUK** [comment] 2018-05-30 16:42
Turns out it wasn't a problem with CMP but rather Sortable. Sortable has a wrapper that goes around the code that executes DFP. In our case, Sortable made a change their end and fixed the issue.

**Comment by krishoyt** [comment] 2018-06-06 22:41
Sounds like this isn't caused by the CMP itself.  Closing for now.

**Closed by krishoyt** 2018-06-06 22:41 UTC
